baseURL = "https://luisdur8.github.io/my_launchx_blog/"
languageCode = "es"
title = "Bitácora de Viaje de luisDur"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquí pon tu twitter 👇
  twitter_handle = "@luisDur_Math"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
